POST http://localhost:4000/user/signUp
Content-Type: application/json

{
    "email":"madhu@gmail.com",
    "password":"madhu12"
}
###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "email":"madhu@gmail.com",
    "password":"madhu12"
}
###
POST http://localhost:4000/recipes/post
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZGh1QGdtYWlsLmNvbSIsImlkIjoiNjdiYTg0YzliMjNiODBjYTczYmI5YTkxIiwiaWF0IjoxNzQwMzAwNzIyLCJleHAiOjE3NDAzMDQzMjJ9.qeJMGVUrAwlAob9O6orLyxtjoXmvjlv3KJj0adHgtmY
Content-Type: application/json

{
    "title":"Biryani",
    "ingredients":["chicken", "powder", "salt"],
    "instructions":"do it good",
    "time":20,
    "imageUrl":"https://res.cloudinary.com/dpd55e6mf/image/upload/v1740277710/biryani_uh8zbh.jpg"
}
###
POST http://localhost:4000/recipes/post
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZGh1QGdtYWlsLmNvbSIsImlkIjoiNjdiYTg0YzliMjNiODBjYTczYmI5YTkxIiwiaWF0IjoxNzQwMjk5MTc1LCJleHAiOjE3NDAzMDI3NzV9.y9JNgyoJDmFnPfzw1SJSQ-5Okz_ONIkD6NAs7dXI2jk
Content-Type: application/json

{
    "title":"chicken fry",
    "ingredients":["chicken", "powder", "salt"],
    "instructions":"do it good",
    "time":20,
    "imageUrl":"https://res.cloudinary.com/dpd55e6mf/image/upload/v1740277710/biryani_uh8zbh.jpg"
}
###
GET http://localhost:4000/recipes/getAll
###
PUT http://localhost:4000/recipes/update/67bae1ffb82a03f750e19815
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZGh1QGdtYWlsLmNvbSIsImlkIjoiNjdiYTg0YzliMjNiODBjYTczYmI5YTkxIiwiaWF0IjoxNzQwMjk5MTc1LCJleHAiOjE3NDAzMDI3NzV9.y9JNgyoJDmFnPfzw1SJSQ-5Okz_ONIkD6NAs7dXI2jk
Content-Type: application/json

{
    "title":"Mutton Biryani",
    "ingredients":["Mutton","rice","powder"]
   

}
###
GET http://localhost:4000/recipes/get/67bae1ffb82a03f750e19815
###
DELETE http://localhost:4000/recipes/delete/67ba865848078272d539c6c8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZGh1QGdtYWlsLmNvbSIsImlkIjoiNjdiYTg0YzliMjNiODBjYTczYmI5YTkxIiwiaWF0IjoxNzQwMjc2OTkxLCJleHAiOjE3NDAyODA1OTF9.VwIvi02eOoGudnyLpytbLBbfnRbqQfE8RDRSNvfCCDA
